version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - HOST_NAME=${HOSTNAME}
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ./healthchecks.sh
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 3s
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    depends_on:
      - node
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - mynetwork

networks:
  mynetwork: